import LocalizedStrings from 'react-localization';
export default new LocalizedStrings({

    ar: {
        totalCount: "العدد الإجمالي",
        controlPanel: "لوحة التحكم",
        next: 'التالي',
        previous: "السابقة",
        page_size: "حجم الصفحة",
        logout: "تسجيل الخروج",
        login: 'دخول',
        price: "السعر",
        imagePickerMaxSizeMessage: "رسالة منتقي الصور بالحجم الأقصى",
        fromTheLink: "من الرابط",
        products: "المنتجات",
        product: "المنتج",
        productsList: "قائمة المنتجات",
        createProduct: 'إنشاء منتج',
        search: 'بحث',
        category: "الفئة",
        description: "وصف",
        name: 'اسم',
        quantity: "الكمية",
        image: "صورة",
        delete: "حذف",
        edit: "تحرير",
        number: "رقم",
        id: 'id',
        doYouWantToDelete: "هل تريد حقًا حذف {0} من السجل نهائيًا؟",
        yes: 'نعم',
        no: 'لا',
        close: "إغلاق",
        categories: "فئات",
        parent: "الاب",
        create: "إنشاء",
        brands: "العلامات التجارية",
        brand: "العلامة التجارية",
        user: "المستخدم",
        users: "المستخدمون",
        order: "ترتيب",
        orders: "الطلبات",
        orderItems: "بنود الطلب",
        orderItem: "طلب البند",
        value: "القيمة",
        username: "اسم المستخدم",
        admins: "مشريفين",
        admin: 'مشرف',
        password: "كلمة المرور",
        phone: "phone",
        phones: "الهواتف",
        signUp: "تسجيل",
        slides: "الشرائح",
        slide: "الشريحة",
        createSlide: 'إنشاء شريحة',
        SlidesList: 'قائمة الشرائح',
        to: "to",

    },


})