import LocalizedStrings from 'react-localization';
export default new LocalizedStrings({
    en: {
        totalCount: 'total count',
        controlPanel: 'control panel',
        next: 'next',
        previous: 'previous',
        page_size: 'page size',
        logout: 'logout',
        login: 'login',
        price: 'price',
        imagePickerMaxSizeMessage: 'image Picker Max Size Message',
        fromTheLink: 'from the link',
        products: 'products',
        product: 'product',
        productsList: 'products list',
        createProduct: 'create product',
        search: 'search',
        category: 'category',
        description: 'description',
        name: 'name',
        quantity: 'quantity',
        image: 'image',
        delete: 'delete',
        edit: 'edit',
        number: 'number',
        id: 'id',
        doYouWantToDelete: 'Do you really want to permanently delete {0} from history?',
        yes: 'yes',
        no: 'no',
        close: 'close',
        categories: 'categories',
        parent: 'parent',
        create: 'create',
        brands: 'brands',
        brand: 'brand',
        user: 'user',
        users: 'users',
        order: 'order',
        orders: 'orders',
        orderItems: 'order items',
        orderItem: 'order item',
        value: 'value',
        username: 'username',
        admins: 'admins',
        admin: 'admin',
        password: 'password',
        phone: 'phone',
        phones: 'phones',
        signUp: 'signUp',
        slides: 'slides',
        slide: 'slide',
        createSlide: 'create slide',
        slidesList: 'slides list',
        to: 'to',


    },
    ar: {
        totalCount: "العدد الإجمالي",
        controlPanel: "لوحة التحكم",
        next: 'التالي',
        previous: "السابقة",
        page_size: "حجم الصفحة",
        logout: "تسجيل الخروج",
        login: 'دخول',
        price: "السعر",
        imagePickerMaxSizeMessage: "رسالة منتقي الصور بالحجم الأقصى",
        fromTheLink: "من الرابط",
        products: "المنتجات",
        product: "المنتج",
        productsList: "قائمة المنتجات",
        createProduct: 'إنشاء منتج',
        search: 'بحث',
        category: "الفئة",
        description: "وصف",
        name: 'اسم',
        quantity: "الكمية",
        image: "صورة",
        delete: "حذف",
        edit: "تحرير",
        number: "رقم",
        id: 'id',
        doYouWantToDelete: "هل تريد حقًا حذف {0} من السجل نهائيًا؟",
        yes: 'نعم',
        no: 'لا',
        close: "قريب",
        categories: "فئات",
        parent: "الاب",
        create: "إنشاء",
        brands: "العلامات التجارية",
        brand: "العلامة التجارية",
        user: "المستخدم",
        users: "المستخدمون",
        order: "ترتيب",
        orders: "الطلبات",
        orderItems: "بنود الطلب",
        orderItem: "طلب البند",
        value: "القيمة",
        username: "اسم المستخدم",
        admins: "admins",
        admin: 'admin',
        password: "كلمة المرور",
        phone: "phone",
        phones: "الهواتف",
        signUp: "تسجيل",
        slides: "الشرائح",
        slide: "الشريحة",
        createSlide: 'إنشاء شريحة',
        SlidesList: 'قائمة الشرائح',
        to: "to",

    },


})