import LocalizedStrings from 'react-localization';
export default new LocalizedStrings({
    en: {
        totalCount: 'total count',
        controlPanel: 'control panel',
        next: 'next',
        previous: 'previous',
        page_size: 'page size',
        logout: 'logout',
        login: 'login',
        price: 'price',
        imagePickerMaxSizeMessage: 'image Picker Max Size Message',
        fromTheLink: 'from the link',
        products: 'products',
        product: 'product',
        productsList: 'products list',
        createProduct: 'create product',
        search: 'search',
        category: 'category',
        description: 'description',
        name: 'name',
        quantity: 'quantity',
        image: 'image',
        delete: 'delete',
        edit: 'edit',
        number: 'number',
        id: 'id',
        doYouWantToDelete: 'Do you really want to permanently delete {0} from history?',
        yes: 'yes',
        no: 'no',
        close: 'close',
        categories: 'categories',
        parent: 'parent',
        create: 'create',
        brands: 'brands',
        brand: 'brand',
        user: 'user',
        users: 'users',
        order: 'order',
        orders: 'orders',
        orderItems: 'order items',
        orderItem: 'order item',
        value: 'value',
        username: 'username',
        admins: 'admins',
        admin: 'admin',
        password: 'password',
        phone:'phone',
        phones:'phones',
        signUp: 'signUp',
        slides: 'slides',
        slide: 'slide',
        createSlide: 'create slide',
        slidesList: 'slides list',

        to: 'to',


    },
    ar: {
        totalCount: 'العدد الكلي',
        controlPanel: 'لوحة التحكم',
        next: 'التالي',
        previous: 'السابق',
        page_size: 'حجم الصفحة',
        logout: 'تسجيل الخروج',
        login: 'تسجيل الدخول',
        doYouWantToDelete: 'هل تود فعلا حدف {0} من السجل بشكل دائما؟',

    },


})