import LocalizedStrings from 'react-localization';
export default new LocalizedStrings({
    ar: {
        create: "انشاء {0}",
        menue: "قائمة",
        listOf: "قائمة ال{0}",

        serviceProvider: "مزود الخدمة",
        serviceProviders: "مزودي الخدمات",
        doctor: "طبيب",
        createDoctor: "تسجيل طبيب",

        doctors: "اطباء",
        contractsAndCompanies: 'العقود والشركات',
        customers: 'مستفدين',
        customer: 'المستفيد',

        doctorAppointment: "موعد الطبيب",
        doctorAppointments: "مواعيد الاطباء",
        claim: 'مطالبة',
        claims: 'مطالبات',
        openClaims: 'المطالبات المفتوحة',
        closedClaims: 'المطالبات المغلقة',
        receivedClaims: 'المطالبات المسلّمة',
        acceptedClaims: 'المطالبات المقبولة',
        rejectedClaims: 'المطالبات المرفوضة',
        suspendedClaims: 'المطالبات المعلقة',
        partiallyAcceptedClaims: 'المطالبات المقبولة جزئياً',
        paidClaims: 'المطالبات المسدودة',
        allClaimsCount: 'العدد الكلي للمطالبات',
        allClaimsTotalValue: 'المجموع الكلي لقيم المطالبات',
        libyanDinar: 'د.ل',
        controlPanel: 'لوحة تحكم',
        openAdmissionCases: 'حالات الايواء المفتوحة',
        nameOf: 'اسم ال{0}',
        name: 'الاسم',
        email: 'بريد',
        password: 'كلمة السر',
        cardNumber: 'رقم البطاقة',
        expirationDate: 'تاريخ انتهاء الصلاحية',
        allowedAmount: 'السـقـف العـام',
        cardAllowedAmount: 'سقف البطاقة',

        country: 'البلد',
        city: 'المدينة',
        address: 'العنوان',
        phoneNumber: 'رقم الهاتف',
        contract: 'العقد',
        isPrinted: 'تم طباعتها',
        birthday: 'تاريخ الميلاد',
        day: 'يوم',
        startTime: 'بداية الدوام',
        endTime: 'نهاية الدوام',

        bills: 'فواتير',
        bill: 'فاتورة',

        editRecord: 'تعديل {0}',
        deleteRecord: 'حدف {0}',
        confirmDeleteMessage: 'هل تود فعلا حدف {0} دائما؟',

        yes: 'نعم',
        no: 'لا',

        login: 'تسجيل الدخول',
        logout: 'تسجيل الخروج',

        claimsAndBills: 'المطالبات و الفواتير',
        servicesAndMedicinces: 'الخدمات والادوية',

        chats: 'المحادثات',

        companiesAndProvidersUsers: 'مستخدمي الشركات والمزودين',
        dashboardUsers: 'مستخدمي لوحة التحكم',

        notifications: 'الاشعارات',
        allNotifications: 'كل الاشعارات',
        myNotifications: 'اشعاراتي',

        usersActivities: 'نشاطات المستخدمين',

        services: 'خدمات',
        medicines: 'ادوية',
        categories: 'تصنيفات',
        companies: 'شركات',
        contracts: 'عقود',
        benefits: 'منافع',
        benefit: 'منفعة',

        receiveClaims: 'استلام المطالبات',
        reviewClaims: 'مراجعة المطالبات',
        payingClaims: 'سداد المطالبات',

        The: 'ال{0}',
        users: 'مستخدمين',
        user: 'مستخدم',
        cardInquiry: 'الاستعلام عن بطاقة',
        chatWithMedicate: 'محادثة مع شركة ميديكيت',

        send: 'إرسال',
        created_at: 'تاريخ الانشاء',
        updated_at: 'تاريخ التعديل',

        description: 'وصف',
        priceOf: 'سعر ال{0}',
        imageOf: 'صورة ال{0}',
        documentsAttackedTo: 'المستندات الملحق بال{0}',
        attachedDocuments: 'المستندات الملحق',

        attachNewDocument: 'الحاق مستند جديد',
        numberOf: 'رقم ال{0}',
        confirmCard: 'تاكد من البطاقة',
        consumed: 'المستهلك',
        benefitsOfCustomer: 'منافع المستفيذ',
        admissionClaim: 'مطالبة ايواء',
        statusOf: 'حالة ال{0}',
        action: 'اجراء',
        typeOf: 'نوع ال{0}',
        closeTheClaim: 'اغلاق المطالبة',
        openTheClaim: 'فتح المطالبة',
        deleteTheClaim: 'حدف المطالبة',
        price: 'السعر',
        customerPayment: 'دفع المستفيد',
        companyPayment: 'دفع الشركة',
        availableCustomerBenefits: 'جدول المنافع المتاحة للمستفيذ',
        availableServicesForBenefit: 'خدماتنا المتاحة للمنفعة',
        weDontHaveMedicinesForCategory: 'ليس لدينا ادوية لهذ التصنيف',
        weDontHaveServicessForCategory: 'ليس لدينا خدمات لهذ التصنيف',

        addNewBill: 'اضف فاتورة جديدة',
        recordNewBills: 'تسجيل الفواتير الجديدة',
        quantity: 'الكمية',
        totalValue: 'القيمة الكلية',
        addressOf: 'عنوان ال',
        arabicNameOf: 'اسم ال{0} بالعربي',
        englishNameOf: 'اسم ال{0} بالانجليزي',
        detailsOf: 'تفاصيل ال{0}',
        activation: 'التفعيل',
        category: 'تصنيف',
        typeOfProvider: 'نوع مزود خدمة',
        selectThe: 'اختر ال{0}',
        type: 'نوع',

        locationOf: 'موقع {0}',
        latitude: 'خط العرض',
        longitude: 'خط الطول',

        admission: 'ايواء',

        specialty: 'تخصص',
        fromTheLink: 'من رابط',
        schedule: 'جدول المواعيد',
        addScheduleAppointment: 'اضف موعد',
        maxCasesNumber: 'اقصى عدد للحالات',
        removeScheduleAppointment: 'ازالة موعد',
        open: 'مفتوح',
        claimsOfServiceProvider: 'مطالبات مزود الخدمة',
        claimsOfContract: 'مطالبات العقد',
        service: 'خدمة',
        categoryOf: 'تصنيف ال{0}',


        closed: 'مغلقة',
        received: 'مستلمة',
        accepted: 'مقبولة',
        rejected: 'مرفوضة',
        suspended: 'معلّقة',
        partially_accepted: 'مقبولة جزئياً',
        paid: 'مسددة',

        notes: 'ملاحظات',
        outpatientClinics: 'عيادات خارجية',
        outpatientClinicsService: 'خدمة عيادات خارجية',
        contactUs: 'اتصل بنا',
        language: 'اللغة',
        providerServices: 'خدمات مزود الخدمة',
        conformClaimNumber: 'تاكد من المطالبة',
        claimBills: 'فواتير المطالبة',
        printBills: 'طباعة الفواتير',
        accept: 'قبول',
        reject: 'رفض',
        suspend: 'تعليق',
        partially_accept: 'قبول جزئيا',
        customerInfo: 'معلومات المستفيذ',
        providerServiceStatistics: 'احصائيات استعمال الخدمات من قبل المستفيدين',
        descriptionOf: 'وصف ال{0}',
        filter: 'فلترة',
        search: 'بحث',
        company: 'شركة',
        firstParty: 'الطرف الاول',
        secondParty: 'الطرف الثاني',
        imagePickerMaxSizeMessage: 'حجم الصورة يجب ان لا يفوق',
        companyPercent: 'نسبة الشركة المستفيذة',
        customerPercent: 'نسبة المستفيذة',
        username: 'اسم المستخدم',
        customerCompany: 'الشركة المستفيذة',
        document: 'مستند',
        providersServicesList: 'قائمة خدمات المزوديين',
        servicesCategoryList: 'قائمة تصنيفات الخدمات',
        printClaimForm: 'طباعة نموذج مطالبة',
        customerConsumption: 'استهلاك المستفيذ',
        cancel: 'الغاء',
        footerMessage: 'كن مخولا لاتخاد أفضل قرار صحي لك و لافراد عائلتك إدراكاً للفجوة السائدة في القطاع الصحي في ليبيا.',
        medicateAddress: 'ليبيا طرابلس - غوط الشعال',
        arabicName: 'الاسم العربي',
        englishName: 'الاسم الانجليزي',
        previous: 'السابق',
        next: 'التالي',
        weDontHaveServicesForThisBenefit: 'ليس لدينا خدمات لهذ المنفعة',
        notification: 'اشعار',
        doYouWantToDelete: 'هل تود فعلا حدف {0} من السجل بشكل دائما؟',
        numberOfClaimsWithCustomer: 'عدد المطالبات مع المستفيذ',
        deleteFromRecords: 'حدف {0} من السجلات',
        usedCustomerBenefits: 'منافع المستفيد المستعملة',
        medicinePrice: 'سعر الدواء',
        numberOfDoses: 'عدد الجرعات',
        categoryOfMedicine: 'تصنيف الدواء',
        medicateForHealth: ' للرعاية الصحية',
        medicineImage: 'صورة الدواء',
        details: 'تفاصيل',
        doctorsAppointmentsList: 'قائمة المواعيد الاطباء',
        claimForm: 'نموذج مطالبة',
        extractClaimForm: 'إستخراج نموذج مطالبة',
        medicine: 'دواء',

        useConditions: 'شروط الاستعمال',
        medicineBills: 'فواتير للدواء',
        medicalNumber: 'الرقم الطبي',
        errorBoundaryMessage: 'خطأ 404',
        edit: 'تعديل',
        delete: 'حدف',
        isCustomerIsAdult: 'هل المستفيد بالغ',
        contractId: 'رقم العقد',
        "App\\Models\\Admin": 'مستخدم للوحة التحكم',
        "App\\Models\\User": 'مستخدم',
        "App\\Models\\ServiceProvider": 'مزود',
        "App\\Models\\Medicine": 'دواء',
        "App\\Models\\Service": 'خدمة',
        medicate: '',
        info: 'معلومات',
        saveClaim: 'حفظ المطالبة',
        deleteClaim: 'الغاء المطالبة',
        reopenClaim: 'اعادة فتح المطالبة',
        setupBill: 'اعداد فاتورة',
        pageSize: 'حجم الصفحة',
        'مصحة': 'مصحة',
        'مختبر': 'مختبر',
        'صيدلية': 'صيدلية',
        'مركز علاج طبيعي': 'مركز علاج طبيعي',
        'مركز سمعيات وبصيريات': 'مركز سمعيات وبصيريات',
        totalCount: 'العدد الكلي',
        customerRecord: 'سجل المستفيد',

        not_received: 'غير مستلمة',
        under_review: 'قيد المراجعة',
        reviewed: 'تمت مراجعتها',
        worthy: 'مستحقة',
        claimStatistics: 'احصائيات المطالبات',
        comment: 'تعليق',
        information: 'معلومات',
        reception: 'استقبال',
        customerInquiry: 'الاستعلام عن مستفيد',
        servicesAndMedicines: 'الخدمات والادوية',
        admin: 'مشرف',
        chooseBenefit: 'إختر التصنيف',

        serviceBills: 'فواتير الخدمات',

        claimNumber: 'رقم المطالبة',
        updated: 'تم تحديث',
        created: 'تم إنشاء',
        typicalPrice: 'السعر المعتاد',
        receivedClaimsValue: 'قيمة المطالبات المستلمة',
        notReceivedClaimsValue: 'قيمة المطالبات الغير مستلمة',
        outPatient: 'عيادات خارجية',
        ambulance: 'اسعاف والطوارئ',
        dental: 'اسنان',
        monitorPanel: 'لوحة المراقبة',
        accountStatement: 'كشف حساب',
        activated: 'مفعّل',
        billsCount: 'عدد الفواتير',
        partially_accepted_value: 'القيمة المقبولة جزئياً',
        inPatient: 'ايواء',
        specialBills: 'فواتير مخصصة',
        can_enter_special_bills: 'بالامكان ادخال فواتير مخصصة',
        status: 'الحالة',

        in_day: 'في اليوم',
        number_of_days: 'عدد الايام',

        payClaims: 'سداد المطالبات',
        payClaim: 'سداد مطالبة',
        payingMultipleClaims: 'سداد عدة مطالبات',
        creator: 'المنشئ',
        nationalNumber: 'الرقم الوطني',
        printed_at: 'تاريخ الطباعة',
        page_size: 'حجم الصفحة',
        medicalNetwork: 'الشبكة الطبية',
        serviceProviderId: 'رقم مزود الخدمة',
        total_value: 'القيمة الكلية',
        printClaim: 'طباعة المطالبة',
        nameInArabic: 'الاسم بالعربي',
        nameInEnglish: 'الاسم بالانجليزية',

        exchangeRate: 'سعر الصرف',
        exchangeRates: 'أسعار الصرف',

        'عملة ليبيا': 'د.ل',
        'عملة تونس': 'د.ت',

    },
})